doctrine:
    dbal:
        dbname: '%env(resolve:PDO_DBNAME)%'
        host: '%env(resolve:PDO_HOST)%'
        user: '%env(resolve:PDO_USER)%'
        password: '%env(resolve:PDO_PASSWD)%'
        driver: pdo_mysql

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
